[
  "tests.py::TestFailure::()::test_bad_checksum"
]